services:
    pgsql:
      container_name: pgsql
      image: postgres
      ports:
        - '5432:5432'
      environment:
          POSTGRES_USER: ${POSTGRES_USER}
          POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
          POSTGRES_DB: ${POSTGRES_DB}
      volumes:
        - ./pgdata_master:/bitnami/postgresql
      restart: unless-stopped
      networks:
        djnet:
          ipv4_address: 172.111.11.10
 
 
networks:
  djnet:
    ipam:
      driver: default
      config:
        - subnet: 172.111.11.0/24
 